name: CI/CD - Docker Build and Push

on:
  push:
    branches:
      - develop
      - mlops
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código del repositorio
        uses: actions/checkout@v2

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t casanova560/mlops-project:latest .

      - name: Subir imagen a Docker Hub
        run: docker push casanova560/mlops-project:latest
